DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS PRODUCT_PACKAGE;

CREATE TABLE USER (
    ID INT AUTO_INCREMENT Primary key,
    FIRST_NAME VARCHAR (60),
    LAST_NAME VARCHAR (60),
    EMAIL VARCHAR(250) UNIQUE );

CREATE TABLE PRODUCT_PACKAGE(
    ID INT AUTO_INCREMENT Primary key,
    USER_NAME VARCHAR(60),
    PACKAGE_NAME VARCHAR(500) UNIQUE,
    PACKAGE_FILE_URL VARCHAR(200),
    REQUEST_QUANTITY VARCHAR(200),
    DUE_DATE DATE,
    NOTES VARCHAR (5000))
