CREATE TABLE users (ID BIGINT auto_increment, USER_NAME VARCHAR (60), EMAIL VARCHAR(250))
INSERT  INTO users(ID, USER_NAME, EMAIL) values ('Test', 'testUser@gmail.com')
CREATE TABLE user_Details(USER_NAME VARCHAR(60), PACKAGE_NAME VARCHAR(500),DUE_DATE DATETIME_INTERVAL_CODE, Notes VARCHAR (5000), )
