DROP TABLE IF EXISTS users;

CREATE TABLE users (
    ID INT AUTO_INCREMENT Primary key,
    FIRST_NAME VARCHAR (60),
    LAST_NAME VARCHAR (60),
    EMAIL VARCHAR(250));

CREATE TABLE user_Details(
    USER_NAME VARCHAR(60),
    PACKAGE_NAME VARCHAR(500),
    PACKAGE_FILE_URL VARCHAR(200),
    REQUEST_QUANTITY VARCHAR(200),
    DUE_DATE DATE,
    NOTES VARCHAR (5000))
